server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/capgemini
    username: capgemini
    password: capgemini
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  sql:
    init:
      mode: never